name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
        run: docker build . --file Dockerfile --tag ${DOCKER_USER}/${REPO_NAME}:${TAG}
      - name: Docker Push
        run: docker push ${DOCKER_USER}/${REPO_NAME}:${TAG}
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
      - name: Choreo Deploy
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO_NAME: ${{ github.event.repository.name }}
          TAG: ${{github.sha}}
          TOKEN: ${{secrets.TOKEN}}
          DOCKER_IMAGE_NAME: ${{secrets.DOCKER_USER}}/${{ github.event.repository.name }}
        run: |
          curl --location --request POST \
          'https://apis.preview-dv.choreo.dev/devops/1.0.0/external-ci/deploy' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "component_id": "1944d2f2-9444-4179-8dae-593d7186715d",
            "version_id": "58de9252-dac9-434b-a282-4a87ff7db6c1",
            "token": "'${TOKEN}'",
            "image": "registry.docker.com/'${DOCKER_IMAGE_NAME}':'${TAG}'"
          }'
